from typing import Dict, Any, List, Optional
from pydantic import BaseModel, Field

class AgentOfficeState(BaseModel):
    """
    Typed shared state for the LangGraph workflow.

    Execution lifecycle fields (new):
    - execution_state: Fine-grained state machine:
        pending → planning → running → testing → fixing → completed | failed
    - workspace_id: Directory name of the per-task isolated workspace (e.g. 'task_abc123')
    - files_created: List of filenames written into the workspace during this task
    - commands_run: Tool calls / commands executed during task (for audit + user-facing summary)
    - verification_passed: Set True once tests/syntax checks succeed
    - memory_context: Additional structured memory context injected before execution

    Core fields:
    - task_id: Unique task identifier
    - user_input: Raw input prompt from the user
    - assigned_agent_id: ID of the selected permanent or newly-spawned temporary agent
    - is_temporary_agent: True if agent was dynamically generated for this task
    - need_rag: Decision flag indicating whether agentic RAG retrieval is required
    - retrieved_rag_context: Chunks extracted from local knowledge base if need_rag is True
    - past_experiences: Distilled organizational lessons retrieved from memory store
    - agent_output: Final text response generated by the agent
    - tools_used: List of tool names called during execution
    - evaluation: Evaluation outcome containing success flag, score (0.0-1.0), and reason
    - retries: Number of refinement attempts made so far
    - max_retries: Safety ceiling to strictly prevent infinite loops (default: 2)
    - status: Current workflow status
    - error: Any runtime error message
    """
    task_id: str
    user_input: str

    # Execution state machine
    execution_state: str = "pending"          # pending|planning|running|testing|fixing|completed|failed

    # Workspace
    workspace_id: Optional[str] = None        # e.g. "task_abc123"
    files_created: List[str] = Field(default_factory=list)
    commands_run: List[str] = Field(default_factory=list)
    verification_passed: bool = False

    # Memory
    memory_context: Optional[str] = None      # additional structured context beyond experiences

    # Agent assignment
    assigned_agent_id: Optional[str] = None
    agent_name: Optional[str] = None
    collaborating_agent_id: Optional[str] = None
    collaborating_agent_name: Optional[str] = None
    is_collaborative: bool = False
    peer_review_notes: Optional[str] = None
    is_temporary_agent: bool = False

    # Retrieval
    need_rag: bool = False
    need_obsidian_knowledge: bool = False   # Manager sets this when Obsidian lookup is useful
    retrieved_rag_context: Optional[str] = None
    past_experiences: Optional[str] = None

    # Output
    agent_output: Optional[str] = None
    tools_used: List[str] = Field(default_factory=list)
    artifacts: Optional[Dict[str, Any]] = None

    # Telemetry
    tokens_used: int = 0
    latency_ms: float = 0.0
    cost_usd: float = 0.0
    start_time: Optional[float] = None

    # Control
    evaluation: Optional[Dict[str, Any]] = None
    retries: int = 0
    max_retries: int = 2
    handled_by_orchestrator: bool = False
    status: str = "pending"
    error: Optional[str] = None
